/* Define the action types e.g.  ACTION_ADD = 'ACTION_ADD' */

export const TOGGLE_GENDER_FILTER = 'TOGGLE_GENDER_FILTER';
export const TOGGLE_TOPIC_FILTER = 'TOGGLE_TOPIC_FILTER';
export const TOGGLE_SERVICE_FILTER = 'TOGGLE_SERVICE_FILTER';
